# ---------------------------------------------------------------------
# Derived from MeloTTS (https://github.com/myshell-ai/MeloTTS)
# Copyright (c) 2024 MyShell.ai
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------
"""English G2P for melo_zh_local (Chinese-English mixed TTS).

Minimal English phoneme conversion matching upstream melo/text/english.py,
but WITHOUT the `transformers` dependency. Uses g2p_en for ARPAbet conversion.

This module is used by chinese.py's _g2p_v2 for English segments.

Performance optimization:
  On ARM64 Windows, ``from g2p_en import G2p`` takes ~14 seconds due to pure-Python
  interpretation overhead.  To avoid paying this cost on every worker startup, we
  support loading a pre-built pickle cache (``vendor/g2p_cache.pkl``) generated by
  ``scripts/setup/predeploy_tts_runtime.py`` during Setup_Env.  The cache contains all
  G2p state (CMUdict, GRU weights, homograph dict) and loads in ~200ms.

  Fallback: if the cache is missing, we fall back to the original ``g2p_en`` import.
"""

import os
import re
import unicodedata
from pathlib import Path

from .symbols import language_tone_start_map

# ARPAbet phoneme set (with stress markers)
arpa = {
    "AH0", "S", "AH1", "EY2", "AE2", "EH0", "OW2", "UH0", "NG",
    "B", "G", "AY0", "M", "AA0", "F", "AO0", "ER2", "UH1", "IY1",
    "AH2", "DH", "IY0", "EY1", "IH0", "K", "N", "W", "IY2", "T",
    "AA1", "ER1", "EH2", "OY0", "UH2", "UW1", "Z", "AW2", "AW1",
    "V", "UW2", "AA2", "ER", "AW0", "UW0", "R", "OW1", "EH1", "ZH",
    "AE0", "IH2", "IH", "Y", "JH", "P", "AY1", "EY0", "OY2", "TH",
    "HH", "D", "ER0", "CH", "AO1", "AE1", "AO2", "OY1", "AY2",
    "IH1", "OW0", "L", "SH",
}

# Lazy-initialized G2p instance (avoids slow import if English is unused)
_g2p_instance = None

# Cache file location: <root>/vendor/g2p_data/g2p_cache.pkl
# Resolved by walking UP for an existing ``vendor/`` dir rather than a fixed
# ``parents[N]`` jump — a fixed jump breaks across layouts (dev repo:
# vendor is parents[5]; packaged app <app>/pack/<id>/melo_zh_local: parents[3]).
# The ancestor-walk finds it in both; None means "no cache, use the live import".
def _find_g2p_cache() -> Path:
    for _parent in Path(__file__).resolve().parents:
        _cand = _parent / "vendor" / "g2p_data" / "g2p_cache.pkl"
        if _cand.is_file():
            return _cand
    # No cache found — return a non-existent canonical path so the
    # ``.is_file()`` guard in _load_g2p_from_cache() falls back cleanly.
    return Path(__file__).resolve().parents[-1] / "vendor" / "g2p_data" / "g2p_cache.pkl"


_G2P_CACHE_PATH = _find_g2p_cache()


def _load_g2p_from_cache():
    """Attempt to restore a G2p instance from the pre-built pickle cache.

    The cache is built by ``scripts/setup/predeploy_tts_runtime.py`` and contains all
    G2p state (CMUdict, GRU weights, homograph dict).  Loading it reconstructs
    a ``_CachedG2p`` object in ~200ms, vs ~14s for the full ``from g2p_en import G2p``.

    Returns a functional G2p-compatible object, or None if cache is missing or
    corrupt (caller falls back to live g2p_en import).
    """
    if not _G2P_CACHE_PATH.is_file():
        return None
    try:
        import pickle
        import numpy  # noqa: F401 — needed at unpickling time for numpy.ndarray reconstruction
        with open(_G2P_CACHE_PATH, "rb") as f:
            data = pickle.load(f)
        return _CachedG2p(data)
    except Exception:
        return None


class _CachedG2p:
    """A G2p-compatible object reconstructed from cached data.

    Replicates the interface of g2p_en.G2p (callable, returns phoneme list)
    without importing g2p_en at all. The GRU inference methods are reimplemented
    here (they're ~20 lines of numpy, same as the original).
    """

    def __init__(self, data: dict):
        self.graphemes = data["graphemes"]
        self.phonemes = data["phonemes"]
        self.g2idx = data["g2idx"]
        self.idx2g = data["idx2g"]
        self.p2idx = data["p2idx"]
        self.idx2p = data["idx2p"]
        self.cmu = data["cmu"]
        self.homograph2features = data["homograph2features"]
        # GRU weights
        self.enc_emb = data["enc_emb"]
        self.enc_w_ih = data["enc_w_ih"]
        self.enc_w_hh = data["enc_w_hh"]
        self.enc_b_ih = data["enc_b_ih"]
        self.enc_b_hh = data["enc_b_hh"]
        self.dec_emb = data["dec_emb"]
        self.dec_w_ih = data["dec_w_ih"]
        self.dec_w_hh = data["dec_w_hh"]
        self.dec_b_ih = data["dec_b_ih"]
        self.dec_b_hh = data["dec_b_hh"]
        self.fc_w = data["fc_w"]
        self.fc_b = data["fc_b"]

    # ── Numpy GRU inference (same as g2p_en.G2p) ─────────────────────────

    def sigmoid(self, x):
        import numpy as np
        return 1 / (1 + np.exp(-x))

    def grucell(self, x, h, w_ih, w_hh, b_ih, b_hh):
        import numpy as np
        rzn_ih = np.matmul(x, w_ih.T) + b_ih
        rzn_hh = np.matmul(h, w_hh.T) + b_hh
        rz_ih, n_ih = rzn_ih[:, :rzn_ih.shape[-1] * 2 // 3], rzn_ih[:, rzn_ih.shape[-1] * 2 // 3:]
        rz_hh, n_hh = rzn_hh[:, :rzn_hh.shape[-1] * 2 // 3], rzn_hh[:, rzn_hh.shape[-1] * 2 // 3:]
        rz = self.sigmoid(rz_ih + rz_hh)
        r, z = rz[:, :rz.shape[-1] // 2], rz[:, rz.shape[-1] // 2:]
        n = np.tanh(n_ih + r * n_hh)
        h = (1 - z) * n + z * h
        return h

    def gru(self, x, h, w_ih, w_hh, b_ih, b_hh):
        for i in range(x.shape[0]):
            h = self.grucell(x[i:i + 1], h, w_ih, w_hh, b_ih, b_hh)
        return h

    def encode(self, word):
        import numpy as np
        chars = list(word) + ["</s>"]
        x = [self.g2idx.get(c, self.g2idx["<unk>"]) for c in chars]
        x = self.enc_emb[x]
        h = np.zeros((1, self.enc_w_hh.shape[-1]), np.float32)
        h = self.gru(x, h, self.enc_w_ih, self.enc_w_hh, self.enc_b_ih, self.enc_b_hh)
        return h

    def decode(self, h):
        import numpy as np
        preds = []
        dec_input = np.array([[self.p2idx["<s>"]]], np.int32)
        for _ in range(20):
            emb = self.dec_emb[dec_input.flatten()]
            h = self.grucell(emb, h, self.dec_w_ih, self.dec_w_hh, self.dec_b_ih, self.dec_b_hh)
            logits = np.matmul(h, self.fc_w.T) + self.fc_b
            pred = logits.argmax(axis=-1).item()
            if pred == self.p2idx["</s>"]:
                break
            preds.append(self.idx2p[pred])
            dec_input = np.array([[pred]], np.int32)
        return preds

    def __call__(self, text):
        """Convert text to phonemes (same interface as g2p_en.G2p.__call__)."""
        import re as _re

        # Normalize: only invoke the expensive normalize_numbers (inflect, 3s)
        # when the text actually contains digits.
        text = str(text)
        if _re.search(r"\d", text):
            normalize_numbers = _get_normalize_numbers()
            text = normalize_numbers(text)
        text = ''.join(c for c in unicodedata.normalize('NFD', text)
                       if unicodedata.category(c) != 'Mn')
        text = text.lower()
        text = _re.sub(r"[^ a-z'.,?!\-]", "", text)
        text = text.replace("i.e.", "that is")
        text = text.replace("e.g.", "for example")

        prons = []
        for word in _tokenize(text):
            if not _re.search("[a-z]", word):
                prons.extend(list(word))
                continue
            if word in self.homograph2features:
                pron1, pron2, pos1 = self.homograph2features[word]
                prons.extend(pron1)  # simplified: always use pron1
            elif word in self.cmu:
                prons.extend(self.cmu[word][0])
            else:
                # OOV: use GRU seq2seq
                h = self.encode(word)
                phs = self.decode(h)
                prons.extend(phs)
        return prons


def _tokenize(text):
    """Simple word tokenizer (replaces NLTK TweetTokenizer dependency)."""
    import re as _re
    return _re.findall(r"[a-z]+(?:'[a-z]+)?|[.,?!\-]", text)


# Cache the normalize_numbers function from g2p_en/expand.py.
# We load it via importlib.util to avoid triggering g2p_en's __init__.py
# (which takes 14s on ARM64 due to nltk + numpy initialization).
_normalize_numbers_fn = None


def _get_normalize_numbers():
    global _normalize_numbers_fn
    if _normalize_numbers_fn is not None:
        return _normalize_numbers_fn
    import importlib.util
    import site
    # Find g2p_en/expand.py in site-packages without importing the package
    for sp in site.getsitepackages() + [site.getusersitepackages()]:
        candidate = os.path.join(sp, "g2p_en", "expand.py")
        if os.path.isfile(candidate):
            spec = importlib.util.spec_from_file_location("_g2p_expand", candidate)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            _normalize_numbers_fn = mod.normalize_numbers
            return _normalize_numbers_fn
    # Last resort: slow import path
    from g2p_en.expand import normalize_numbers  # type: ignore[import]
    _normalize_numbers_fn = normalize_numbers
    return _normalize_numbers_fn


def _get_g2p():
    global _g2p_instance
    if _g2p_instance is None:
        # Try fast cache path first (200ms vs 14s)
        cached = _load_g2p_from_cache()
        if cached is not None:
            _g2p_instance = cached
        else:
            # Fallback: full g2p_en import (slow on ARM64)
            from g2p_en import G2p
            _g2p_instance = G2p()
    return _g2p_instance


def refine_ph(phn):
    """Extract tone from ARPAbet phoneme (e.g., 'AH1' -> ('ah', 2))."""
    tone = 0
    if re.search(r"\d$", phn):
        tone = int(phn[-1]) + 1
        phn = phn[:-1]
    return phn.lower(), tone


def post_replace_ph(ph):
    """Map special phones to the melo symbol set."""
    from .symbols import symbols
    rep_map = {
        "v": "V",
    }
    if ph in rep_map:
        ph = rep_map[ph]
    if ph in symbols:
        return ph
    return "UNK"


def distribute_phone(n_phone, n_word):
    """Distribute n_phone phonemes across n_word sub-word tokens.

    Copied from melo/text/japanese.py distribute_phone.
    """
    phones_per_word = [0] * n_word
    for i in range(n_phone):
        min_tasks = min(phones_per_word)
        min_index = phones_per_word.index(min_tasks)
        phones_per_word[min_index] += 1
    return phones_per_word


def g2p(text=None, pad_start_end=True, tokenized=None):
    """Convert English text/tokens to (phones, tones, word2ph).

    Matches the upstream melo/text/english.py g2p() signature.

    Args:
        text: English text string (unused if tokenized is provided)
        pad_start_end: Whether to wrap with "_" padding
        tokenized: list of WordPiece tokens (from BERT tokenizer)

    Returns:
        (phones, tones, word2ph) where phones are lowercase ARPAbet symbols
    """
    g2p_func = _get_g2p()

    if tokenized is None:
        # Simple fallback: split by whitespace/punctuation
        if text is None:
            return [], [], []
        words = re.split(r"([,;.\-\?\!\s+])", text)
        tokenized_groups = [[w] for w in words if w.strip()]
    else:
        # Group ##-prefixed sub-tokens with their root token
        ph_groups = []
        for t in tokenized:
            if not t.startswith("#"):
                ph_groups.append([t])
            else:
                if ph_groups:
                    ph_groups[-1].append(t.replace("#", ""))
                else:
                    ph_groups.append([t.replace("#", "")])
        tokenized_groups = ph_groups

    phones = []
    tones = []
    word2ph = []

    for group in tokenized_groups:
        w = "".join(group)
        phone_len = 0
        word_len = len(group)

        phone_list = list(filter(lambda p: p != " ", g2p_func(w)))
        for ph in phone_list:
            if ph in arpa:
                ph, tn = refine_ph(ph)
                phones.append(ph)
                tones.append(tn)
            else:
                phones.append(ph)
                tones.append(0)
            phone_len += 1

        aaa = distribute_phone(phone_len, word_len)
        word2ph += aaa

    phones = [post_replace_ph(i) for i in phones]

    if pad_start_end:
        phones = ["_"] + phones + ["_"]
        tones = [0] + tones + [0]
        word2ph = [1] + word2ph + [1]

    return phones, tones, word2ph
