# ---------------------------------------------------------------------
# Copyright (c) 2026 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------

"""Value objects for the ai_coding bounded context.

This module gathers the immutable, equality-by-value building blocks of
the AI coding domain.  Following the S2 conventions (see
``docs/90-refactor/S2-sub-agent-spec.md`` §4.1) every value object is a
``@dataclass(frozen=True, slots=True, kw_only=True)`` so callers cannot
accidentally mutate identifiers, paths or message payloads.

Design notes
------------
* The :class:`Provider` enum unifies what was previously two parallel
  implementations (``ClaudeCodeSessionManager`` and the OpenCode session
  manager) into a single aggregate.  The choice of provider is captured
  on :class:`CodingSession`; it does NOT trigger any new
  cross-implementation duplication.
* :class:`Workspace` carries an absolute filesystem path string but does
  not perform any I/O — the domain layer must remain pure.  Validation
  is delegated to ``qai.platform.io_validator``.
* :class:`CodingStreamFrame` is the wire-shape of a single SSE frame
  emitted by the streaming use case.  It is intentionally provider-
  agnostic so the chat / app_builder contexts can adopt it later.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from qai.platform.io_validator import (
    assert_max_length,
    assert_no_control_chars,
    assert_non_empty,
)

__all__ = [
    "CodingSessionConfig",
    "CodingSessionId",
    "CodingStreamFrame",
    "HookConfig",
    "HookEvent",
    "McpServerConfig",
    "MessageContent",
    "OutputFormat",
    "PermissionDecision",
    "PermissionRequestId",
    "Provider",
    "SessionStatus",
    "StreamFrameKind",
    "ToolInvocationId",
    "ToolName",
    "Workspace",
]


# ---------------------------------------------------------------------------
# Identifier value objects
# ---------------------------------------------------------------------------
@dataclass(frozen=True, slots=True, kw_only=True)
class CodingSessionId:
    """Opaque identifier of a :class:`CodingSession` aggregate.

    The wrapped string is generated by an injected ``IdGenerator`` and
    must be a non-empty, control-char-free token.  No further structure
    is assumed: the persistence layer is free to use ULID, UUIDv7 or
    any other opaque format.
    """

    value: str

    def __post_init__(self) -> None:
        assert_non_empty(self.value, name="value")
        assert_max_length(self.value, max_length=128, name="value")
        assert_no_control_chars(self.value, name="value")

    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True, slots=True, kw_only=True)
class PermissionRequestId:
    """Identifier for a single :class:`PermissionRequest` entity."""

    value: str

    def __post_init__(self) -> None:
        assert_non_empty(self.value, name="value")
        assert_max_length(self.value, max_length=128, name="value")
        assert_no_control_chars(self.value, name="value")

    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True, slots=True, kw_only=True)
class ToolInvocationId:
    """Identifier for a single :class:`ToolInvocation` entity."""

    value: str

    def __post_init__(self) -> None:
        assert_non_empty(self.value, name="value")
        assert_max_length(self.value, max_length=128, name="value")
        assert_no_control_chars(self.value, name="value")

    def __str__(self) -> str:
        return self.value


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------
class Provider(str, Enum):
    """The coding-agent backend that powers a session.

    Subclassing ``str`` keeps JSON serialisation simple and makes
    comparisons with literal strings ergonomic in tests.
    """

    CLAUDE_CODE = "claude_code"
    OPEN_CODE = "open_code"


class SessionStatus(str, Enum):
    """State machine for :class:`CodingSession`.

    Allowed transitions (see :mod:`qai.ai_coding.domain.entities`):

    .. code-block:: text

        PENDING --> ACTIVE --> STREAMING --> ACTIVE
                |       |        |
                |       |        +--> PERMISSION_REQUESTED --> ACTIVE
                |       v
                |    IDLE --> ACTIVE
                v
            TERMINATED
    """

    PENDING = "pending"
    ACTIVE = "active"
    IDLE = "idle"
    STREAMING = "streaming"
    PERMISSION_REQUESTED = "permission_requested"
    TERMINATED = "terminated"


class PermissionDecision(str, Enum):
    """Outcome of a :class:`PermissionRequest`.

    ``PENDING`` is the implicit initial state and is also exposed as a
    distinct value so the persistence layer can serialise it directly.
    """

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


class StreamFrameKind(str, Enum):
    """Logical kind of a streaming frame surfaced to the caller."""

    TEXT = "text"
    TOOL_CALL = "tool_call"
    TOOL_RESULT = "tool_result"
    PERMISSION_REQUEST = "permission_request"
    ERROR = "error"
    END = "end"
    # Task/Agent sub-task frames (V1 parity: session_manager.py:2044-2079).
    # Tail-appended — does not change existing values/ordering, so the
    # locked SSE frame format (§3.1) is preserved. Like PERMISSION_REQUEST,
    # the native Anthropic HTTP SSE wire does not emit these today; they are
    # surfaced when an upstream agent runtime injects task_started /
    # task_progress / task_notification events (the front-end builds the V1
    # "🤖 sub-tasks" cards from them).
    TASK_STARTED = "task_started"
    TASK_PROGRESS = "task_progress"
    TASK_NOTIFICATION = "task_notification"


# ---------------------------------------------------------------------------
# Plain value objects
# ---------------------------------------------------------------------------
@dataclass(frozen=True, slots=True, kw_only=True)
class Workspace:
    """An absolute path identifying the working directory of a session.

    The domain treats the path as an opaque string; there are no
    filesystem calls here.  ``WorkspaceLockPort`` (in the application
    layer) is the seam for "is this workspace already in use?" checks.
    """

    path: str

    def __post_init__(self) -> None:
        assert_non_empty(self.path, name="path")
        assert_max_length(self.path, max_length=4096, name="path")
        assert_no_control_chars(self.path, name="path")

    def __str__(self) -> str:
        return self.path


@dataclass(frozen=True, slots=True, kw_only=True)
class ToolName:
    """Symbolic name of a tool exposed to the coding agent.

    Examples (mirroring the legacy ``backend/tools/registry.py`` set):
    ``"file.read"``, ``"shell.exec"``, ``"app_builder.run"``.  The
    domain itself enforces no specific list — ``SkillRegistryPort`` and
    ``ToolBridgePort`` decide which names actually resolve.
    """

    value: str

    def __post_init__(self) -> None:
        assert_non_empty(self.value, name="value")
        assert_max_length(self.value, max_length=128, name="value")
        assert_no_control_chars(self.value, name="value")

    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True, slots=True, kw_only=True)
class MessageContent:
    """Free-form chat message text supplied by the user."""

    text: str

    def __post_init__(self) -> None:
        assert_non_empty(self.text, name="text")
        # 256 KiB upper-bound — generous for prompts without enabling DoS.
        assert_max_length(self.text, max_length=256 * 1024, name="text")


@dataclass(frozen=True, slots=True, kw_only=True)
class CodingStreamFrame:
    """One frame yielded by a streaming coding session.

    ``payload`` is intentionally typed as ``dict[str, Any]`` rather than
    a tagged union: each :class:`StreamFrameKind` carries a different
    payload shape and the application layer is responsible for
    interpreting it.  This keeps the domain contract minimal and lets
    the SSE adapter forward frames verbatim.
    """

    kind: StreamFrameKind
    payload: dict[str, Any]
    sequence: int

    def __post_init__(self) -> None:
        if self.sequence < 0:
            raise ValueError("sequence must be >= 0")


# ---------------------------------------------------------------------------
# PR-107: SDK 12-item enhancements (legacy parity)
# ---------------------------------------------------------------------------
# These value objects carry the configuration that the legacy
# ``backend/ai_coding/session_manager.py`` ferried into the
# ``ClaudeAgentOptions`` constructor — mcp_servers, hooks (10 events),
# fallback_model, output_format, etc.  They are *value objects* not
# entities: equality is by value and they are immutable so the
# application layer can pass them around freely without aliasing
# concerns.
# ---------------------------------------------------------------------------


class HookEvent(str, Enum):
    """The 10 hook events the legacy SDK could intercept around a turn.

    Names mirror the lifecycle order::

        on_session_start
            -> on_user_input
                -> pre_message
                    -> pre_tool_call -> post_tool_call
                -> post_message
            -> on_complete | on_truncate | on_error
        on_session_end

    Each :class:`HookConfig` carries one event + a shell command +
    optional timeout.  These hooks are *reserved* fields — no provider
    consumes them today (the SDK-backed CC provider does not splat them
    onto its ``ClaudeAgentOptions``); the provider merely persists the
    configuration on the session handle so a future hook-dispatch engine
    can read it back.  This keeps the wire body clean (these hooks are
    local-only side effects, not Anthropic API parameters).
    """

    PRE_TOOL_CALL = "pre_tool_call"
    POST_TOOL_CALL = "post_tool_call"
    PRE_MESSAGE = "pre_message"
    POST_MESSAGE = "post_message"
    ON_ERROR = "on_error"
    ON_COMPLETE = "on_complete"
    ON_USER_INPUT = "on_user_input"
    ON_SESSION_START = "on_session_start"
    ON_SESSION_END = "on_session_end"
    ON_TRUNCATE = "on_truncate"


class OutputFormat(str, Enum):
    """Output rendering format requested by the caller.

    ``text`` is the default streaming text.  ``json`` and ``structured``
    are post-stream renderers — a *reserved* field no provider consumes
    today, so it never lands in the Anthropic wire body.
    """

    TEXT = "text"
    JSON = "json"
    STRUCTURED = "structured"


@dataclass(frozen=True, slots=True, kw_only=True)
class McpServerConfig:
    """One Model Context Protocol server the session may consult.

    Three transports are supported by Anthropic's MCP-client beta:
    ``stdio`` (spawn a local process), ``sse`` (Server-Sent Events
    over HTTP) and ``websocket``.  The transport string is opaque to
    this domain layer; the provider validates it at wire-mapping time.

    ``auth`` is a free-form dict so callers can provide ``{"type":
    "bearer", "token": "..."}`` or ``{"type": "oauth", ...}``;
    the provider redacts secret-looking values before logging.
    """

    name: str
    url: str
    transport: str = "stdio"
    auth: dict[str, str] = field(default_factory=dict)

    def __post_init__(self) -> None:
        assert_non_empty(self.name, name="name")
        assert_max_length(self.name, max_length=128, name="name")
        assert_no_control_chars(self.name, name="name")
        assert_non_empty(self.url, name="url")
        assert_max_length(self.url, max_length=4096, name="url")
        assert_no_control_chars(self.url, name="url")
        assert_non_empty(self.transport, name="transport")
        assert_max_length(self.transport, max_length=32, name="transport")


@dataclass(frozen=True, slots=True, kw_only=True)
class HookConfig:
    """One hook registration: event + shell command + timeout."""

    event: HookEvent
    command: str
    timeout_s: float = 30.0

    def __post_init__(self) -> None:
        assert_non_empty(self.command, name="command")
        assert_max_length(self.command, max_length=4096, name="command")
        assert_no_control_chars(self.command, name="command")
        if self.timeout_s <= 0:
            raise ValueError("timeout_s must be > 0")


@dataclass(frozen=True, slots=True, kw_only=True)
class CodingSessionConfig:
    """The 12 SDK enhancements ferried per session (PR-107).

    Every field is optional with a benign default so a session
    spawned without any extras (the historical PR-046 / PR-102 path)
    keeps working unchanged.

    Fields by destination
    ---------------------
    Wire-body (Anthropic Messages API):

    * :attr:`mcp_servers` — flattened into the request body's
      ``mcp_servers`` array; requires beta header
      ``anthropic-beta: mcp-client-2025-04-04`` set by the provider.
    * :attr:`max_budget_usd` — surfaced inside ``metadata.max_budget_usd``
      so the upstream's billing pipeline can throttle the request.
    * :attr:`fallback_model` — surfaced inside ``metadata.fallback_model``
      so Anthropic Messages can pick an alternate weight when the
      primary returns 5xx.
    * :attr:`task_budget` — surfaced inside ``metadata.task_budget``
      (turn budget; legacy ``ClaudeAgentOptions.max_turns`` analogue).
    * :attr:`user` — surfaced as top-level ``metadata.user_id`` (the
      Anthropic recommended "stable user identifier" field).
    * :attr:`extra_args` — every key/value flat-merged into
      ``metadata`` (operator escape hatch for vendor-specific knobs).

    Local-only / out-of-band (NOT in the Anthropic wire body):

    * :attr:`hooks` — pre/post tool-call shell commands (10 event
      types). The Anthropic API has no equivalent so the provider
      stores them on the session handle and exposes them via
      :meth:`HttpCodingProviderBase.session_config`.  *Reserved* field:
      no provider consumes them today (a future hook-dispatch engine
      would read them back).
    * :attr:`output_format` — output rendering (text / json /
      structured).  Anthropic always streams text.  *Reserved* field:
      no provider reformats the stream today.
    * :attr:`setting_sources` — ordered list of override origins for
      merging configurations (e.g. ``("project", "user", "global")``).
      *Reserved* field: not consumed by any provider today.
    * :attr:`plugins` — plugin names enabled this turn.  *Reserved*
      field: not consumed by any provider today.
    * :attr:`session_env` — environment variables injected into the CLI
      subprocess env (legacy ``ClaudeAgentOptions.env`` analogue).
      Consumed by the SDK-backed CC provider
      (:class:`ClaudeCodeSdkProvider._build_session_env`).
    * :attr:`skills` — F-23 (PR-I3): per-session skill filter, the
      ``ClaudeAgentOptions.skills`` analogue.  Distinct from the
      ``manage_skills`` mount-style skill (which provisions skill
      content into the session); ``skills`` here is a *filter* listing
      which skill names the session is allowed to use this turn.
      Empty tuple means "no per-session filter — use whatever
      ``manage_skills`` mounted".  *Reserved* field, not in the wire
      body: when the agent runtime supports per-session skill scoping it
      would read this list to constrain the catalog of skills/tools
      surfaced to the model.  V2 当前 agent 路径 = ``qai.chat`` 流式工具
      循环; per-session 过滤的具体接线由接通方决定 (参见 GAP-PLAN F-2
      决策: 保留代码但暂不接线).
    """

    mcp_servers: tuple[McpServerConfig, ...] = ()
    hooks: tuple[HookConfig, ...] = ()
    max_budget_usd: float | None = None
    fallback_model: str | None = None
    output_format: OutputFormat = OutputFormat.TEXT
    task_budget: int | None = None
    setting_sources: tuple[str, ...] = ()
    plugins: tuple[str, ...] = ()
    extra_args: dict[str, str] = field(default_factory=dict)
    user: str | None = None
    session_env: dict[str, str] = field(default_factory=dict)
    # PR-104a: thinking-depth override (legacy ``effort`` interface).
    # Append-only field per v2.7 §3.1; keeps the historical PR-046 /
    # PR-102 / PR-107 spawn paths working unchanged.  Allowed values
    # mirror the legacy CLI: ``low``, ``medium``, ``high``, ``max``.
    # ``None`` means "use the global default" (the SDK-backed CC
    # provider decides).  Consumed by ``ClaudeCodeSdkProvider`` when set.
    effort: str | None = None
    # F-23 (PR-I3): per-session skill filter (``ClaudeAgentOptions.skills``
    # analogue).  Append-only field per v2.7 §3.1; benign default ``()``
    # means "no filter".  Reserved — not splatted onto the wire body and
    # not consumed by any provider today (see ``claude_code.py`` L516
    # routing comment).
    skills: tuple[str, ...] = ()
    # 2-H6: explicit thinking-config override (V1 ``session.thinking`` /
    # ``ClaudeAgentOptions.thinking``).  Append-only per v2.7 §3.1.
    # Distinct from :attr:`effort` (a coarse CLI keyword) — ``thinking``
    # is the structured SDK ``ThinkingConfig`` payload (e.g.
    # ``{"type": "enabled", "budget_tokens": 16000}``).  V1 only honoured
    # a dict whose ``type`` was set (``session_manager.py:1719-1722``);
    # ``None`` means "no explicit thinking config — fall back to effort /
    # the global default".  The provider routes this into the Anthropic
    # wire body (2-H7).  Stored as an immutable mapping snapshot.
    thinking: dict[str, str | int] | None = None
    # 2-H8: SDK ``ClaudeAgentOptions`` directory / sub-agent / beta knobs
    # (V1 ``session_manager.py:1698-1774``).  Append-only per v2.7 §3.1.
    #   * ``add_dirs`` — extra workspace directories the agent may read
    #     (V1 ``add_dirs``); the provider forwards them in the wire body.
    #   * ``agents`` — named sub-agent definitions (V1 ``agents``); a
    #     mapping of agent-name → opaque definition payload.
    #   * ``betas`` — Anthropic beta feature flags (V1 ``betas``, e.g.
    #     ``"context-1m-2025-08-07"``); forwarded as the ``anthropic-beta``
    #     header / wire field.
    # All default to empty so the historical spawn paths are unchanged;
    # the provider only emits a wire key when the corresponding tuple /
    # mapping is non-empty (2-H8).
    add_dirs: tuple[str, ...] = ()
    agents: tuple[str, ...] = ()
    betas: tuple[str, ...] = ()
    # ── CC SDK file-checkpoint backend (V1 ``session_manager.py``) ──────
    # These three fields drive the SDK-backed Claude Code provider that
    # mirrors V1's ``claude_agent_sdk`` short-connection model (resume +
    # ``enable_file_checkpointing`` true file restore on disk).  Append-only
    # per v2.7 §3.1; all default to the V1 defaults so the historical HTTP
    # spawn paths are byte-for-byte unchanged.
    #
    #   * ``cc_backend`` — ``"http"`` (default) keeps the pure-HTTP Anthropic
    #     Messages adapter; ``"sdk"`` opts into the ``claude_agent_sdk`` CLI
    #     subprocess adapter (real file checkpoint/rewind).  The DI root
    #     gracefully falls back to ``"http"`` when the SDK / CLI is missing.
    #   * ``cli_path`` — explicit path to a native ``claude`` CLI executable
    #     (V1 ``ClaudeAgentOptions.cli_path``; ``session_manager.py:1446-
    #     1448,1833``).  Empty string means "auto-locate" (the SDK provider
    #     runs :func:`locate_claude_cli`).  A ``.cmd`` shim is rewritten to
    #     the sibling ``.exe`` so the SDK pipe handshake works.
    #   * ``enable_file_checkpointing`` — V1 default ``False``
    #     (``session_manager.py:1725``, has I/O overhead); the operator
    #     opts in via the settings panel.  When ``True`` the SDK provider
    #     passes ``enable_file_checkpointing=True`` +
    #     ``extra_args={"replay-user-messages": None}`` so it can capture
    #     ``UserMessage.uuid`` for ``rewind_files``.
    cc_backend: str = "http"
    cli_path: str = ""
    enable_file_checkpointing: bool = False

    def __post_init__(self) -> None:
        if self.cc_backend not in {"http", "sdk"}:
            raise ValueError(
                f"cc_backend must be 'http' or 'sdk', got {self.cc_backend!r}"
            )
        if self.cli_path:
            assert_max_length(self.cli_path, max_length=4096, name="cli_path")
            assert_no_control_chars(self.cli_path, name="cli_path")
        if self.max_budget_usd is not None and self.max_budget_usd < 0:
            raise ValueError("max_budget_usd must be >= 0")
        if self.task_budget is not None and self.task_budget < 0:
            raise ValueError("task_budget must be >= 0")
        if self.fallback_model is not None:
            assert_non_empty(self.fallback_model, name="fallback_model")
            assert_max_length(
                self.fallback_model, max_length=128, name="fallback_model"
            )
            assert_no_control_chars(
                self.fallback_model, name="fallback_model"
            )
        if self.user is not None:
            assert_non_empty(self.user, name="user")
            assert_max_length(self.user, max_length=128, name="user")
            assert_no_control_chars(self.user, name="user")
        for key, value in self.extra_args.items():
            assert_no_control_chars(key, name="extra_args.key")
            assert_no_control_chars(value, name="extra_args.value")
        for key, value in self.session_env.items():
            assert_no_control_chars(key, name="session_env.key")
            assert_no_control_chars(value, name="session_env.value")
        # Reject duplicate hook events to keep hook dispatch
        # deterministic — the legacy ``ClaudeAgentOptions`` accepted a
        # mapping (one entry per event) so we mirror that constraint.
        seen: set[HookEvent] = set()
        for hook in self.hooks:
            if hook.event in seen:
                raise ValueError(
                    f"duplicate hook event: {hook.event.value!r}"
                )
            seen.add(hook.event)
        # PR-104a: validate ``effort`` against the legacy CLI value set.
        if self.effort is not None and self.effort not in {
            "low", "medium", "high", "max",
        }:
            raise ValueError(
                f"effort must be one of: low, medium, high, max "
                f"(got {self.effort!r})"
            )
        # F-23: validate per-session skill names.  Same field-level
        # constraints as other identifier-like tuples on this VO
        # (non-empty, length-bounded, no control chars).  Duplicate
        # names are rejected to keep the per-session skill-filter
        # logic deterministic.
        seen_skills: set[str] = set()
        for skill in self.skills:
            assert_non_empty(skill, name="skills")
            assert_max_length(skill, max_length=128, name="skills")
            assert_no_control_chars(skill, name="skills")
            if skill in seen_skills:
                raise ValueError(f"duplicate skill: {skill!r}")
            seen_skills.add(skill)
        # 2-H6: validate the optional thinking config.  V1 only honoured
        # a dict whose ``type`` key was set (``session_manager.py:1719-
        # 1722``); an empty / type-less mapping is rejected so a malformed
        # override never reaches the wire.
        if self.thinking is not None and not self.thinking.get("type"):
            raise ValueError(
                "thinking config must carry a non-empty 'type' key"
            )
        # 2-H8: validate add_dirs / agents / betas (identifier-/path-like
        # tuples).  Non-empty, length-bounded, no control chars — same
        # discipline as ``skills`` above.
        for field_name, values in (
            ("add_dirs", self.add_dirs),
            ("agents", self.agents),
            ("betas", self.betas),
        ):
            for value in values:
                assert_non_empty(value, name=field_name)
                assert_max_length(value, max_length=4096, name=field_name)
                assert_no_control_chars(value, name=field_name)
