# ---------------------------------------------------------------------
# Copyright (c) 2026 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------

"""Filesystem helpers for the ``app_pack/`` directory layout.

Direct port of the legacy
``features/model-builder/scripts/qai_pack_export.py`` helpers:

* ``_link_or_copy`` — best-effort symlink + copy fallback (Windows
  non-admin / FAT32 hosts can't ``os.symlink``);
* ``_clean_for_re_export`` — incremental cleanup that keeps the heavy
  ``examples/`` / ``provenance/`` / ``weights/`` / ``assets/`` trees
  across re-exports;
* ``sha256_file`` — streaming SHA-256 over a context binary;
* ``find_context_binary`` — locate ``<model>_<label>.bin`` (label
  form) or ``<model>_<plan>.bin`` (plan form) under ``output/`` with
  case-insensitive fallback;
* ``collect_example_images`` — first ``MAX_EXAMPLES`` images under
  ``output/`` (sorted by name).
"""

from __future__ import annotations

import hashlib
import os
import shutil
import time
from pathlib import Path

from qai.model_builder.domain import Precision
from qai.model_builder.domain.value_objects import MIN_CONTEXT_BIN_SIZE

__all__ = [
    "MAX_EXAMPLES",
    "IMAGE_EXTENSIONS",
    "STALE_TOP_FILES",
    "PACK_KEEP_DIRS",
    "GENERATING_SENTINEL",
    "CANDIDATE_FILE",
    "GENERATING_STALE_SECONDS",
    "sha256_file",
    "link_or_copy",
    "clean_for_re_export",
    "mark_generating",
    "clear_generating",
    "probe_export_status",
    "find_context_binary",
    "collect_example_images",
]


MAX_EXAMPLES = 3
"""Number of example outputs copied into ``examples/`` per Pack."""

IMAGE_EXTENSIONS: tuple[str, ...] = (
    ".png", ".jpg", ".jpeg", ".bmp", ".tiff", ".webp",
)

STALE_TOP_FILES: tuple[str, ...] = (
    "manifest.json",
    "runner.py",
    "requirements.txt",
    "_candidate.json",
    ".imported_at",
)
"""Top-level files always regenerated by re-export."""

PACK_KEEP_DIRS: tuple[str, ...] = (
    "examples", "provenance", "weights", "assets",
)

GENERATING_SENTINEL = ".generating"
"""In-flight marker written to ``app_pack/`` while an export runs.

The auto-export route is synchronous (it blocks until the whole 13-step
pipeline finishes), so the ONLY durable record that generation is under
way lives on disk: this sentinel is written at the start of the export
(before any long-running step) and removed in a ``finally`` when the
export returns — success OR failure. The Import panel polls
``probe_export_status`` on (re)open so a user who closes the window
mid-generation still sees "生成中..." on reopen instead of the initial
button (the frontend ``exporting`` ref is ephemeral and lost on close).
"""

CANDIDATE_FILE = "_candidate.json"
"""Top-level structural marker written LAST by the export (step 13).

Its presence is the authoritative "generation finished" signal used by
both the dry-run candidate resolver and ``probe_export_status``.
"""

GENERATING_STALE_SECONDS = 3600.0
"""Age after which a lingering ``.generating`` sentinel is treated as stale.

A crash / hard-kill between ``mark_generating`` and ``clear_generating``
would otherwise strand the panel in a permanent "生成中..." state. If the
sentinel is older than this and no ``_candidate.json`` exists, the status
probe reports ``idle`` so the user can retry. One hour comfortably
exceeds a real multi-precision export (minutes).
"""


def sha256_file(path: Path) -> str:
    """Stream-hash ``path`` and return its hex digest."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def link_or_copy(src: Path, dst: Path) -> None:
    """Best-effort symlink ``src`` → ``dst``, falling back to copy.

    Used to materialise per-variant context binaries inside
    ``app_pack/weights/`` without duplicating the multi-hundred-MB
    files when the host platform supports symlinks.

    Failure modes (``OSError`` / ``NotImplementedError``) are
    swallowed in favour of ``shutil.copy2`` — Windows non-admin and
    FAT32 hosts cannot ``os.symlink`` and we'd rather burn the disk
    than refuse to build the Pack.
    """
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        try:
            dst.unlink()
        except OSError:
            pass
    try:
        os.symlink(src, dst)
        return
    except (OSError, NotImplementedError):
        shutil.copy2(src, dst)


def clean_for_re_export(
    pack_dir: Path,
    *,
    keep: tuple[str, ...] = PACK_KEEP_DIRS,
) -> None:
    """Incremental cleanup of an existing ``app_pack/`` directory.

    Removes the always-regenerated top-level files (manifest /
    runner / requirements / _candidate / .imported_at) plus any
    ``__pycache__`` left behind by a previous compile-check, but
    preserves the subdirectories listed in ``keep`` so re-export
    does not have to re-collect example outputs, provenance reports,
    or the per-variant weight files.

    Files outside ``keep`` at the top level that are NOT in
    :data:`STALE_TOP_FILES` are left alone — caller owns them.
    """
    if not pack_dir.is_dir():
        return
    for name in STALE_TOP_FILES:
        f = pack_dir / name
        if f.is_file():
            try:
                f.unlink()
            except OSError:
                pass
    pyc = pack_dir / "__pycache__"
    if pyc.is_dir():
        shutil.rmtree(pyc, ignore_errors=True)
    # ``keep`` is consulted by callers that want to know what to
    # preserve; the function itself only removes what's listed above.
    _ = keep


def mark_generating(pack_dir: Path) -> None:
    """Write the in-flight ``.generating`` sentinel into ``pack_dir``.

    Called once at the very start of an export, before the pipeline's
    long-running steps, so a concurrent Import-panel (re)open can observe
    that generation is under way. Also removes any stale ``_candidate.json``
    from a previous export so ``probe_export_status`` cannot report a fresh
    run as already ``generated`` before it actually finishes. Best-effort:
    a failure to write the sentinel must not abort the export.
    """
    try:
        pack_dir.mkdir(parents=True, exist_ok=True)
        stale = pack_dir / CANDIDATE_FILE
        if stale.is_file():
            try:
                stale.unlink()
            except OSError:
                pass
        (pack_dir / GENERATING_SENTINEL).write_text(
            _now_iso(), encoding="utf-8"
        )
    except OSError:
        pass


def clear_generating(pack_dir: Path) -> None:
    """Remove the ``.generating`` sentinel. Best-effort, idempotent.

    Called in a ``finally`` when the export returns (success or failure)
    so the transient in-flight state never outlives the request.
    """
    try:
        (pack_dir / GENERATING_SENTINEL).unlink()
    except OSError:
        pass


def probe_export_status(workdir: Path) -> str:
    """Report the on-disk export state of ``<workdir>/app_pack`` as a token.

    Returns one of:

    * ``"generated"`` — ``_candidate.json`` exists (export finished);
    * ``"generating"`` — the ``.generating`` sentinel exists, is not stale
      (younger than :data:`GENERATING_STALE_SECONDS`) and no candidate is
      present yet;
    * ``"idle"`` — neither (never generated, or a stale/abandoned run).

    ``_candidate.json`` wins over the sentinel so a completed export whose
    ``clear_generating`` did not run (e.g. hard kill after step 13) still
    reports ``generated``.
    """
    pack_dir = workdir / "app_pack"
    if (pack_dir / CANDIDATE_FILE).is_file():
        return "generated"
    sentinel = pack_dir / GENERATING_SENTINEL
    if sentinel.is_file():
        try:
            age = time.time() - sentinel.stat().st_mtime
        except OSError:
            age = 0.0
        if age <= GENERATING_STALE_SECONDS:
            return "generating"
    return "idle"


def _now_iso() -> str:
    """UTC ISO-8601 timestamp for the sentinel body (diagnostic only)."""
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).isoformat()


def find_context_binary(
    output_dir: Path,
    *,
    model_name: str,
    precision: Precision,
) -> Path | None:
    """Locate the context binary under ``output_dir``.

    Real Model Builder pipelines write filenames using BOTH:

    * label form ``<model>_<label>.bin`` — e.g. ``inception_v3_int8.bin``;
    * plan form  ``<model>_<plan>.bin``  — e.g. ``inception_v3_w8a8.bin``.

    The app_pack contract is format-neutral: the NPU weight may be a QNN
    context binary (``.bin``) OR a QNN DLC (``.dlc``) — ``QNNContext`` loads
    either directly (a ``.dlc`` is numerically equivalent, only ~20-27%
    slower). Model Hub downloads AI Hub ``.dlc`` packages that should promote
    to the SAME app_pack as a Model-Builder-converted ``.bin`` WITHOUT lying
    about the extension. So we probe ``.bin`` FIRST (Model Builder's own
    output; keeps existing behaviour) then ``.dlc`` (AI Hub downloads), for
    each of the label / plan suffix forms, with case-insensitive fallback.
    Returns the path when the file exists and meets
    :data:`qai.model_builder.domain.value_objects.MIN_CONTEXT_BIN_SIZE`,
    else ``None``.
    """
    label = precision.label
    plan = precision.plan_key

    candidate_names: list[str] = []
    seen: set[str] = set()
    # ``.bin`` first (Model Builder native output), then ``.dlc`` (AI Hub /
    # Model Hub downloads). Both are valid app_pack weight formats.
    for ext in (".bin", ".dlc"):
        for suffix in (label, plan):
            bin_name = f"{model_name}_{suffix}{ext}"
            if bin_name.lower() in seen:
                continue
            seen.add(bin_name.lower())
            candidate_names.append(bin_name)

    bin_path: Path | None = None
    for bin_name in candidate_names:
        cand = output_dir / bin_name
        if cand.is_file():
            bin_path = cand
            break
        # Case-insensitive fallback inside output_dir.
        if output_dir.is_dir():
            for f in output_dir.iterdir():
                if f.name.lower() == bin_name.lower() and f.is_file():
                    bin_path = f
                    break
            if bin_path is not None:
                break

    if bin_path is None:
        return None

    try:
        size = bin_path.stat().st_size
    except OSError:
        return None
    if size < MIN_CONTEXT_BIN_SIZE:
        return None
    return bin_path


def collect_example_images(output_dir: Path) -> list[Path]:
    """Up to :data:`MAX_EXAMPLES` example images sorted by name.

    Mirrors the legacy ``collect_example_images`` exactly: ``.png`` /
    ``.jpg`` / ``.jpeg`` / ``.bmp`` / ``.tiff`` / ``.webp``.
    """
    if not output_dir.is_dir():
        return []
    images: list[Path] = []
    for f in sorted(output_dir.iterdir()):
        if f.is_file() and f.suffix.lower() in IMAGE_EXTENSIONS:
            images.append(f)
        if len(images) >= MAX_EXAMPLES:
            break
    return images
